project_id = "ubyphxyyjuglbgfkaals"

[functions.send-notification]
verify_jwt = false

[functions.generate-blog-post]
verify_jwt = false

[functions.scheduled-blog-post]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.send-blog-notification]
verify_jwt = false

[functions.share-blog-social]
verify_jwt = false

[functions.notify-admin-blog]
verify_jwt = false
